In [1]:
import sklearn
import numpy as np
import pandas as pd

In [6]:
def compute_GridSearchCV(kernels,Regularization):
  from sklearn.datasets import load_iris
  x,y=load_iris(return_X_y=True,as_frame=True)
  from sklearn.model_selection import train_test_split
  x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
  from sklearn.svm import SVC
  model=SVC(gamma='auto',random_state=0)
  parm_grid=[{'kernel':kernels,'C':Regularization}]
  from sklearn.model_selection import GridSearchCV
  grid_search=GridSearchCV(model,parm_grid,cv=4)
  grid_search.fit(x_train,y_train)
  return(grid_search.best_score_)

In [4]:
kernels = ['linear' , 'rbf']
Regularization = [1,15,25]

In [7]:
compute_GridSearchCV(kernels,Regularization)

0.9807692307692308

In [61]:
data=pd.read_csv('/content/Social_Network_Ads.csv')

In [62]:
data

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [63]:
x=data.drop('Purchased',axis=1)
y=data['Purchased']

In [64]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [65]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.fit_transform(x_test)

In [66]:
x_train_scaled.shape,x_test_scaled.shape

((300, 2), (100, 2))

In [67]:
from sklearn.svm import SVC
svc=SVC(kernel='linear',random_state=0)

In [68]:
svc.fit(x_train_scaled,y_train)

SVC(kernel='linear', random_state=0)

In [69]:
y_pred=svc.predict(x_test_scaled)

In [70]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(accuracy_score(y_test,y_pred))
print(cm)

0.88
[[63  5]
 [ 7 25]]


In [73]:
from sklearn.datasets import fetch_openml
x,y=fetch_openml('mnist_784',version=1,as_frame=True,return_X_y=True)

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [74]:
x_train=x[:20000]
x_test=x[20000:25000]
y_train=y[:20000]
y_test=y[20000:25000]

In [81]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC

In [87]:
from sklearn.pipeline import Pipeline
pipe=Pipeline([('scaler',MinMaxScaler()),('classifier',SVC(kernel='linear',class_weight=None,decision_function_shape='ovr'))])

In [88]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('scaler', MinMaxScaler()),
                ('classifier', SVC(kernel='linear'))])

In [89]:
y_pred=pipe.predict(x_test)

In [90]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score,f1_score
cm=confusion_matrix(y_test,y_pred)

In [92]:
print(cm)

[[469   0   1   0   0   5   1   1   1   0]
 [  1 555   2   4   0   1   1   1   3   0]
 [  5   4 479   6   9   1   3   6   7   1]
 [  3   3  13 462   0  19   0   3   9   4]
 [  2   0   6   0 468   1   2   4   1  16]
 [ 14   0   0  18   2 405   3   2   7   9]
 [  1   2   2   0   6   9 471   0   0   0]
 [  0   2   4   1   7   1   0 483   0   6]
 [  3  10  11  15   0  19   6   3 396   3]
 [  3   6   1   2  21   0   0  26   2 435]]


In [93]:
469+555+479+462+468+405+471+483+396+435


4623

In [96]:
precision_score(y_test,y_pred,average='weighted'),recall_score(y_test,y_pred,average='weighted'),f1_score(y_test,y_pred,average='weighted')

(0.9245834577056025, 0.9246, 0.9242341822537996)

In [97]:
from sklearn.datasets import fetch_openml
x,y=fetch_openml('mnist_784',version=1,as_frame=True,return_X_y=True)

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [98]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.50,random_state=42)

In [100]:
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [101]:
from sklearn.pipeline import Pipeline
pipe=Pipeline([('scaler',StandardScaler()),('classifier',SVC(kernel='poly',class_weight='balanced',decision_function_shape='ovr',C=10))])

In [102]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=10, class_weight='balanced', kernel='poly'))])

In [103]:
y_pred=pipe.predict(x_test)

In [106]:
from sklearn.metrics import f1_score
f1_score(y_test,y_pred,average='weighted')

0.9723258740744225

In [110]:
def compute_score(x_train, y_train, x_test, y_test):
  from sklearn.svm import SVC
  model=SVC(kernel='poly',C=10,gamma='auto',)
  model.fit(x_train,y_train)
  y_pred=model.predict(x_test)
  from sklearn.metrics import accuracy_score
  return(accuracy_score(y_test,y_pred))

In [111]:
from sklearn.datasets import load_iris
x,y=load_iris(return_X_y=True,as_frame=True)

In [112]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [113]:
compute_score(x_train, y_train, x_test, y_test)

1.0

In [114]:
def compute_score(x_train, y_train, x_test, y_test):
  from sklearn.svm import SVC
  model=SVC(kernel='sigmoid',C=25,gamma='auto',)
  model.fit(x_train,y_train)
  y_pred=model.predict(x_test)
  from sklearn.metrics import accuracy_score
  return(accuracy_score(y_test,y_pred))

In [115]:
compute_score(x_train, y_train, x_test, y_test)

0.28888888888888886

In [173]:
from sklearn.datasets import load_iris

In [189]:
data=load_iris(as_frame=True)

In [185]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [190]:
idx=np.where(data['target']!=0)

In [191]:
idx

(array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
         76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
        115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
        128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143, 144, 145, 146, 147, 148, 149]),)

In [194]:
x=data['data'][50:]
y=data['target'][50:]

In [195]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [196]:
from sklearn.pipeline import Pipeline

In [198]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC

In [200]:
pipe=Pipeline([('scaler',MinMaxScaler()),('classifier',SVC())])

In [201]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('scaler', MinMaxScaler()), ('classifier', SVC())])

In [202]:
y_pred=pipe.predict(x_test)

In [203]:
from sklearn.metrics import precision_score

In [205]:
precision_score(y_test,y_pred,average='micro')

0.92