In [1]:
import sklearn
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00488/Live_20210128.csv")
data

status_id status_type status_published  num_reactions  num_comments  \
0             1       video   4/22/2018 6:00            529           512   
1             2       photo  4/21/2018 22:45            150             0   
2             3       video   4/21/2018 6:17            227           236   
3             4       photo   4/21/2018 2:29            111             0   
4             5       photo   4/18/2018 3:22            213             0   
...         ...         ...              ...            ...           ...   
7045       7046       photo   9/24/2016 2:58             89             0   
7046       7047       photo  9/23/2016 11:19             16             0   
7047       7048       photo  9/21/2016 23:03              2             0   
7048       7049       photo   9/20/2016 0:43            351            12   
7049       7050       photo  9/10/2016 10:30             17             0   

      num_shares  num_likes  num_loves  num_wows  num_hahas  num_sads  \
0            262        432         92         3          1         1   
1              0        150          0         0          0         0   
2             57        204         21         1          1         0   
3              0        111          0         0          0         0   
4              0        204          9         0          0         0   
...          ...        ...        ...       ...        ...       ...   
7045           0         89          0         0          0         0   
7046           0         14          1         0          1         0   
7047           0          1          1         0          0         0   
7048          22        349          2         0          0         0   
7049           0         17          0         0          0         0   

      num_angrys  Column1  Column2  Column3  Column4  
0              0      NaN      NaN      NaN      NaN  
1              0      NaN      NaN      NaN      NaN  
2              0      NaN      NaN      NaN      NaN  
3              0      NaN      NaN      NaN      NaN  
4              0      NaN      NaN      NaN      NaN  
...          ...      ...      ...      ...      ...  
7045           0      NaN      NaN      NaN      NaN  
7046           0      NaN      NaN      NaN      NaN  
7047           0      NaN      NaN      NaN      NaN  
7048           0      NaN      NaN      NaN      NaN  
7049           0      NaN      NaN      NaN      NaN  

[7050 rows x 16 columns]

In [3]:
data.shape

(7050, 16)

In [4]:
data.isna().sum()

status_id              0
status_type            0
status_published       0
num_reactions          0
num_comments           0
num_shares             0
num_likes              0
num_loves              0
num_wows               0
num_hahas              0
num_sads               0
num_angrys             0
Column1             7050
Column2             7050
Column3             7050
Column4             7050
dtype: int64

In [5]:
data=data.drop('Column1',axis=1)

In [6]:
data=data.drop('Column2',axis=1)

In [7]:
data=data.drop('Column3',axis=1)
data=data.drop('Column4',axis=1)

In [8]:
y=data['status_type']

In [9]:
data['status_type'].unique()

array(['video', 'photo', 'link', 'status'], dtype=object)

In [10]:
x=data.drop("status_id",axis=1)

In [11]:
x=x.drop("status_type",axis=1)

In [12]:
x=x.drop("status_published",axis=1)

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [14]:
y_scaled=le.fit_transform(y)

In [15]:
y_scaled

array([3, 1, 3, ..., 1, 1, 1])

In [16]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()

In [17]:
x_scaled=ss.fit_transform(x)

In [18]:
x_scaled

array([[ 0.64610394,  0.32335035,  1.6868788 , ...,  0.07671305,
         0.47357035, -0.15574803],
       [-0.17319166, -0.25220622, -0.3041444 , ..., -0.17600986,
        -0.152587  , -0.15574803],
       [-0.00673846,  0.01308938,  0.12901714, ...,  0.07671305,
        -0.152587  , -0.15574803],
       ...,
       [-0.49312768, -0.25220622, -0.3041444 , ..., -0.17600986,
        -0.152587  , -0.15574803],
       [ 0.26131603, -0.23871662, -0.13695924, ..., -0.17600986,
        -0.152587  , -0.15574803],
       [-0.46070173, -0.25220622, -0.3041444 , ..., -0.17600986,
        -0.152587  , -0.15574803]])

In [19]:
from sklearn.cluster import KMeans
kmeans=KMeans(n_clusters=2)

In [20]:
kmeans.fit(x_scaled)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=2)

In [21]:
kmeans.inertia_

48278.09824220544

In [22]:
kmeans=KMeans(n_clusters=4,random_state=10)

In [23]:
kmeans.fit(x_scaled)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=4, random_state=10)

In [29]:
labels=kmeans.predict(x_scaled)

In [30]:
labels

array([1, 1, 1, ..., 1, 1, 1], dtype=int32)

In [31]:
print(sum(y_scaled==labels))

4421


In [33]:
from sklearn.cluster import AgglomerativeClustering
agc=AgglomerativeClustering(n_clusters=4,affinity='euclidean',linkage='ward')

In [37]:
y_pred=agc.fit_predict(x_scaled)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_agglomerative.py:983: FutureWarning: Attribute `affinity` was deprecated in version 1.2 and will be removed in 1.4. Use `metric` instead
  warnings.warn(


In [38]:
y_pred

array([3, 3, 3, ..., 3, 3, 3])

In [39]:
agc.n_leaves_

7050

In [40]:
from sklearn.metrics import accuracy_score

In [42]:
accuracy_score(y_scaled,y_pred)*100

28.496453900709216