In [1]:
import sklearn
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import fetch_openml


In [3]:
x,y=fetch_openml('mnist_784',version=1,return_X_y=True)

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [4]:
x.shape

(70000, 784)

In [5]:
y[2022]

'2'

In [7]:
x.to_numpy()[2022].mean()

27.761479591836736

In [90]:
digit=x.to_numpy()[2022]
count=0
for i in digit:
  if(i==0):
    count+=1
count

643

In [9]:
x_train=x[:10000]

In [10]:
x_test=x[10000:12000]


In [11]:
y_train=y[:10000]

In [12]:
y_test=y[10000:12000]

In [13]:
y_train.unique()

['5', '0', '4', '1', '9', '2', '3', '6', '7', '8']
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [14]:
y_train.value_counts()

1    1127
7    1070
3    1032
6    1014
0    1001
2     991
4     980
9     978
8     944
5     863
Name: class, dtype: int64

In [15]:
positive_class=6
negative_class=9

In [20]:
idx_6=np.where(y_train=='6')[0]

In [21]:
idx_6

array([  13,   18,   32, ..., 9961, 9967, 9997])

In [24]:
x_train=x_train.to_numpy()

In [91]:
x_train_positive=x_train[idx_9]

In [39]:
idx_9=np.where(y_train=='9')

In [92]:
x_train_negative=x_train[idx_9]

In [51]:
x_train_positive=x_train_positive.astype(int)

In [52]:
x_train_negative=x_train_negative.astype(int)

In [147]:
data_matrix=np.concatenate((x_train_positive,x_train_negative),axis=0)

In [148]:
data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [94]:
y_train_positive=np.ones(len(x_train_positive))

In [95]:
y_train_negative=-1*np.ones(len(x_train_negative))

In [155]:
label_matrix=np.concatenate((y_train_positive,y_train_negative))

In [156]:
label_matrix

array([ 1.,  1.,  1., ..., -1., -1., -1.])

In [157]:
from sklearn.utils import shuffle

In [158]:
data_matrix,label_matrix=shuffle(data_matrix,label_matrix,random_state=1729)

In [159]:
label_matrix[:3]

array([ 1.,  1., -1.])

In [160]:
from sklearn.linear_model import Perceptron

In [172]:
pc=Perceptron(eta0=1,random_state=1729,max_iter=10,fit_intercept=True,shuffle=False,penalty=None)

In [173]:
pc.fit(data_matrix,label_matrix)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:702: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


Perceptron(eta0=1, max_iter=10, random_state=1729, shuffle=False)

In [174]:
##weight vector after 10 iteration
w=pc.coef_[0]

In [175]:
##value of the 69 thfeature(68th indexed feature)
w_69=w[68]

In [176]:
w_69

0.0

In [181]:
intercept=[]
for i in range(5):
  pc.fit(data_matrix,label_matrix)
  intercept.append(pc.intercept_)
intercept

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:702: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:702: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:702: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:702: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic

[array([-74.]), array([-74.]), array([-74.]), array([-74.]), array([-74.])]